name: Docker CI (Contrôle Qualité + Signal Jenkins)

on:
  push:
    branches: [ "main" ]

jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v4

    - name: Test de fabrication de l'image Docker
      run: |
        docker build -t mon-site-test:latest .
        echo "✅ L'image Docker s'est construite sans aucune erreur !"

    # 🧙‍♂️ C'EST ICI QUE LA MAGIE NOIRE OPÈRE : L'appel secret à Jenkins
    - name: Envoyer le signal de déploiement à Jenkins
      run: |
        echo "Envoi du signal à Jenkins..."
        curl -X POST -u "admin:${{ secrets.JENKINS_TOKEN }}" "${{ vars.JENKINS_URL }}/job/devops2026/build"